import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { styled } from "styled-components";

const Home: NextPage = () => {
  return (
    <StyledPageWrapped>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <StyledContentWrapped>
        <h1>
          Welcome to <Link href="https://nextjs.org">Next.js!</Link>
        </h1>
      </StyledContentWrapped>

      <footer>
        <p>
          By <strong>Talismar Fernandes Costa</strong>
        </p>
      </footer>
    </StyledPageWrapped>
  );
};

export default Home;

const StyledPageWrapped = styled.div`
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  gap: 3rem;
  align-items: center;
`;

const StyledContentWrapped = styled.main`
  h1 a {
    color: #000dff;
  }
`;
